webtalk_init -webtalk_dir C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.sim/sim_1/behav/xsim/xsim.dir/TB_VGA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May  6 16:55:27 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "159392eb-2999-4d8d-aefb-1dbae489854e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "777385b49c3d43d09bb6abe5d782de8f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6947914013 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "77.65_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 935609908 -regid "" -xml C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.sim/sim_1/behav/xsim/xsim.dir/TB_VGA_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.sim/sim_1/behav/xsim/xsim.dir/TB_VGA_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.sim/sim_1/behav/xsim/xsim.dir/TB_VGA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
