# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel.xci
# IP: The module: 'clk_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel.xci
# IP: The module: 'clk_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/gblan/OneDrive/Documenten/Vivado_projects/Pong/Pong.srcs/sources_1/ip/clk_pixel/clk_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
